config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :boodles
  resources :comments

  get '/options' => 'main#options'
  get '/stylishness' => 'main#stylishness'
  root 'main#index'

end

app/models/boodle.rb
class Boodle < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  def emojis
    result = []
    comments.each do |comment|
      result.concat(comment.counts_by_emoji.keys)
    end
    result.join('')
  end

  def to_s
    title
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :boodle


  def counts_by_emoji
    emojis = EmojiData.scan(message)
    result=Hash.new
    emojis.each do |emoji|
      result[emoji] ||= 0
      result[emoji] += 1
    end
    result
  end

  def to_s
    message
  end
end

app/models/selfie.rb
class Selfie < ActiveRecord::Base
  belongs_to :user
end

app/models/story_part.rb
class StoryPart < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :boodles
  has_many :selfies
  belongs_to :user_type

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.create_with_password(email)
    password_length = 8
    password = Devise.friendly_token.first(password_length)
    User.create(email: email, password: password)
  end

  def self.fake
    user = create_with_password("#{Devise.friendly_token.first(6)}@test.com")
    Boodle.create(user: user, title: Devise.friendly_token.first(6))
    Comment.create!(boodle: Boodle.first, :message => "sending you love")
    Comment.create!(boodle: Boodle.first, :message => "hahaha")
  end

  def self.next_boodle(user)
    if user.boodles.length == 0
      title = 'My Breasts Are'
    else
      title = StoryPart.all[rand(StoryPart.all.length - 1)].description
    end

    Boodle.new(user: user, title: title)
  end

end

app/models/user_type.rb
class UserType < ActiveRecord::Base
  has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boodles_controller.rb
class BoodlesController < ApplicationController
  before_action :set_boodle, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, :except => [:index, :show]

  # GET /boodles
  # GET /boodles.json
  def index
    @boodles = Boodle.order(created_at: :desc)
  end

  # GET /boodles/1
  # GET /boodles/1.json
  def show
  end


  # GET /boodles/new
  def new
    @boodle = User.next_boodle(current_user)
  end

  # GET /boodles/1/edit
  def edit
  end

  # POST /boodles
  # POST /boodles.json
  def create
    @boodle = Boodle.new(boodle_params)
    @boodle.user = current_user

    respond_to do |format|
      if @boodle.save
        format.html { redirect_to @boodle, notice: 'Boodle was successfully created.' }
        format.json { render :show, status: :created, location: @boodle }
      else
        format.html { render :new }
        format.json { render json: @boodle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boodles/1
  # PATCH/PUT /boodles/1.json
  def update
    respond_to do |format|
      if @boodle.update(boodle_params)
        format.html { redirect_to @boodle, notice: 'Boodle was successfully updated.' }
        format.json { render :show, status: :ok, location: @boodle }
      else
        format.html { render :edit }
        format.json { render json: @boodle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boodles/1
  # DELETE /boodles/1.json
  def destroy
    @boodle.destroy
    respond_to do |format|
      format.html { redirect_to boodles_url, notice: 'Boodle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boodle
      @boodle = Boodle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boodle_params
      params.require(:boodle).permit(:title, :data_url)
    end
    
    def temp_user
      User.find(1)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  # POST /boodles
  # POST /boodles.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.boodle, notice: 'Comment was successfully created.' }
      else
        format.html { redirect_to @comment.boodle, notice: 'Comment was failed to be created.' }
      end
    end
  end

  # DELETE /boodles/1
  # DELETE /boodles/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @comment.boodle, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:message, :boodle_id)
    end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
  end
  
  def stylishness
  end
  
  def options
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boodles_helper.rb
module BoodlesHelper
end

app/views/boodles/_boodle_color_selection.html.erb
<div class="tools u-pull-left">
  <a href="#boodle-canvas" class="color cfff" data-color="#fff"></a>
  <a href="#boodle-canvas" class="color cea8bbc" data-color="#ea8bbc"></a>
  <a href="#boodle-canvas" class="color cb7a2cf" data-color="#b7a2cf"></a>
  <a href="#boodle-canvas" class="color c49c5dc" data-color="#49c5dc"></a>
  <a href="#boodle-canvas" class="color c9ec081" data-color="#9ec081"></a>
  <a href="#boodle-canvas" class="color cfdc64a" data-color="#fdc64a"></a>
  <a href="#boodle-canvas" class="color cff7b10" data-color="#ff7b10"></a>
  <a href="#boodle-canvas" class="color cc6132a" data-color="#c6132a"></a>
</div>

app/views/boodles/_boodle_container.erb
<div class="boodle-container">

  <div class="tools">
    <a href="#boodle-canvas" class="color cfff" data-color="#fff"></a>
    <a href="#boodle-canvas" class="color c000" data-color="#000"></a>
    <a href="#boodle-canvas" class="color cf00" data-color="#f00"></a>
    <a href="#boodle-canvas" class="color c0f0" data-color="#0f0"></a>
    <a href="#boodle-canvas" class="color c00f" data-color="#00f"></a>
    <br />
    <a href="#boodle-canvas" data-tool="marker">Marker</a>
    <a href="#boodle-canvas" data-tool="eraser">Eraser</a>
    <a href="#boodle-canvas" data-download="png">Download</a>
  </div>

  <canvas id="boodle-canvas">
  </canvas>

</div>

app/views/boodles/_boodle_container.html.erb
<div class="boodle-container">

  <%= render 'boodle_color_selection' %>



</div>

app/views/boodles/_form.html.erb
<%= form_for(@boodle) do |f| %>
    <% if @boodle.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@boodle.errors.count, "error") %> prohibited this boodle from being saved:</h2>

          <ul>
            <% @boodle.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% if @boodle.title.blank? %>
        <%= f.label :title, "What's on your mind?" %> <%= f.text_field :title %>
    <% else %>
        <%= f.text_field :title %>
    <% end %>


    <div class="tool-palatte">
      <%= render 'boodle_color_selection' %>
      <div class='create-boodle'>
    </div>
      <%= f.submit :class => 'u-pull-right', :value=> 'Save'%>
    </div>
    <canvas id="boodle-canvas">
    </canvas>


    <%= hidden_field(:boodle, :data_url) %>

<% end %>

app/views/boodles/edit.html.erb
<h1>Editing Boodle</h1>

<%= render 'form' %>

<%= link_to 'Show', @boodle %> |

app/views/boodles/index.html.erb
<% @boodles.each do |boodle| %>
    <div class='boodle preview'>
      <a href="<%= url_for(boodle) %>">
        <div class='info'>
          <%= boodle.user.user_type.emoji unless boodle.user.user_type.nil? %>
          <%= boodle.title %>
        </div>
        <img src="<%= boodle.data_url %>" />
        <div class='info bottom'>
          <%= boodle.emojis %>
          <% if boodle.emojis.blank? %>
          new
          <% end %>
        </div>
      </a>
    </div>
<% end %>

app/views/boodles/new.html.erb
<h1></h1>
<h2></h2>

<%= render 'form' %>

app/views/boodles/show.html.erb
<div class='boodle'>
  <div class="info">
    <%= @boodle.title %>
  </div>
  <img src="<%= @boodle.data_url %>" />

  <div class='info'>
    <% if @boodle.user == current_user %>
        <%= link_to '⛔️', @boodle, method: :delete, data: {confirm: 'Are you sure?'} %> |
    <% end %>
    <%= link_to '⏎', boodles_path %>
  </div>
</div>

<h3>Comments</h3>

<%= form_for(Comment.new(:boodle_id => @boodle.id)) do |f| %>
  <%= hidden_field(:comment, :boodle_id, :value => @boodle.id) %>
  
  <!-- columns should be the immediate child of a .row -->
  <div class="row">
    <div class="nine columns">
      <%= f.text_field :message %>
    </div>
    <div class="three columns right">
      <%= f.submit "Add" %>
    </div>
  </div>

<% end %>

<ul>
  <% @boodle.comments.each do |comment| %>
    <li><%= comment.message -%></li>
  <%- end -%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Boodle</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'favicon/apple-touch-icon-57x57.png'%>">
  <link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'favicon/apple-touch-icon-60x60.png'%>">
  <link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'favicon/apple-touch-icon-72x72.png'%>">
  <link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'favicon/apple-touch-icon-76x76.png'%>">
  <link rel="icon" type="image/png" href="<%= image_path 'favicon/favicon-32x32.png'%>" sizes="32x32">
  <link rel="icon" type="image/png" href="<%= image_path 'favicon/favicon-96x96.png'%>" sizes="96x96">
  <link rel="icon" type="image/png" href="<%= image_path 'favicon/favicon-16x16.png'%>" sizes="16x16">
  <link rel="manifest" href="<%= image_path 'favicon/manifest.json'%>">
  <meta name="msapplication-TileColor" content="#00aba9">
  <meta name="theme-color" content="#ffffff">
</head>
<body id="<%= controller_name -%>-controller" class="<%= action_name -%>-action">

<header>
  <div class="container">
    <div class="logo"><a href="<%= root_path %>"> <%= image_tag('logotype.png') %> </a></div>
    <%= link_to 'Create', new_boodle_path, :class => "right" %>
  </div>
</header>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/main/index.html.erb
<section class="main-image" xmlns="http://www.w3.org/1999/html">
  <div class="boobs-row row">
    <%= image_tag 'boodle_index.jpg' %>
  </div>
</section>

<section class="row promo-row">
  <div class="column twelve center">
    <h2>A Picture Tells a Thousand Words.</h2>
  </div>
</section>

<section class=" how-it-works">

  <div class="row how-row " >
    <div class="one-half column center">
      <%= image_tag 'draw2.png' %>
    </div>
    <div class="one-half column">
      <p>Our bodies have a thousand stories. Some bring laughs, some bring tears. Boodle is your opportunity to tell your
        story.</p>
    </div>
  </div>

  <div class="row how-row " >
    <div class="one-half column center">
      <%= image_tag 'hands.png' %>
    </div>
    <div class="one-half column">
      <p>Browse through the collection of stories, sharing your thoughts, prayers and experiences with other women.</p>
    </div>
  </div>

</section>

app/views/main/options.html.erb
<% if user_signed_in? %>
  <li>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
<% else %>
  <li>
    <%= link_to('Login', new_user_session_path) %>
  </li>
<% end %>

app/views/main/stylishness.html.erb
<h1 class="heading">HTML Basics</h1>
<h1>&lt;h1 /&gt; Heading 1</h1>
<h2>&lt;h2 /&gt; Heading 2</h2>
<h3>&lt;h3 /&gt; Heading 3</h3>
<h4>&lt;h4 /&gt; Heading 4</h4>
<h5>&lt;h5 /&gt; Heading 5</h5>
<h6>&lt;h6 /&gt; Heading 6</h6>
<p>&lt;p /&gt; A paragraph of lorem ipsum morbi vestibulum malesuada posuere. Sed libero sapien, fringilla eget lacus vitae, sagittis egestas enim. Aliquam eu elementum turpis. Donec varius ac nisl at gravida. Nam lacinia ipsum eget enim ullamcorper fermentum. Sed at mollis magna. Aenean aliquet ipsum enim. Nunc consectetur tortor non condimentum ultrices. Nullam sodales felis urna, vitae luctus quam adipiscing ac. Aenean ultrices massa quis ligula luctus, vel commodo dui commodo. Mauris sit amet erat ultricies, rhoncus sapien et, vestibulum metus. Pellentesque iaculis ultricies sem vel posuere. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
<a href="#">&lt;a /&gt; Anchor</a><br />
<em>&lt;em /&gt; Emphasis</em><br />
<strong>&lt;strong /&gt; Strong</strong>